# Example GitHub Workflow Integration for Rolling Baseline Analysis
#
# This workflow demonstrates how to integrate the 7-day rolling baseline
# analysis into your strategic planning workflow.

name: Strategic Planning with Rolling Baseline

on:
  schedule:
    # Run daily at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

env:
  SCREEPS_TOKEN: ${{ secrets.SCREEPS_TOKEN }}
  SCREEPS_HOST: 'screeps.com'
  SCREEPS_SHARD: 'shard3'
  SCREEPS_USERNAME: 'ralphschuler'
  GRAFANA_SERVICE_ACCOUNT_TOKEN: ${{ secrets.GRAFANA_SERVICE_ACCOUNT_TOKEN }}

jobs:
  strategic-analysis:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Need full history for baselines
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Pull Docker images for MCP servers
        run: |
          docker pull ghcr.io/ralphschuler/screeps-mcp:latest
          docker pull mcp/grafana:latest
      
      - name: Collect current metrics
        env:
          RUN_ID: ${{ github.run_id }}
          RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          VERBOSE: 'true'
        run: |
          node scripts/collect-strategic-metrics.mjs \
            performance-baselines/strategic/collected-metrics.json
      
      - name: Compile TypeScript modules
        run: |
          cd scripts/strategic
          npx tsc utils.ts calculate-rolling-baseline.ts detect-regressions.ts generate-trend-report.ts \
            --module node16 --target es2020 --moduleResolution node16 --esModuleInterop
      
      - name: Run rolling baseline analysis
        env:
          ROLLING_DAYS: '7'
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
          BASELINES_DIR: 'performance-baselines/strategic'
          VERBOSE: 'true'
        run: |
          node scripts/strategic/integrate-rolling-baseline.mjs \
            performance-baselines/strategic/collected-metrics.json
      
      - name: Upload baseline artifacts
        uses: actions/upload-artifact@v4
        with:
          name: strategic-baselines-${{ github.run_id }}
          path: |
            performance-baselines/strategic/*_${{ github.run_id }}.json
            performance-baselines/strategic/*_${{ github.run_id }}_report.md
          retention-days: 90
      
      - name: Commit and push baselines
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add performance-baselines/strategic/*.json
          git add performance-baselines/strategic/*.md
          git commit -m "chore(baselines): add strategic baseline for run ${{ github.run_id }}" || true
          git push || true
      
      - name: Check for critical regressions
        id: check_regressions
        run: |
          # Extract health score from latest baseline
          LATEST_BASELINE=$(ls -t performance-baselines/strategic/*_${{ github.run_id }}.json | head -1)
          
          if [ -f "$LATEST_BASELINE" ]; then
            HEALTH_SCORE=$(jq -r '.detectedChanges.healthScore // 100' "$LATEST_BASELINE")
            REGRESSIONS=$(jq -r '.detectedChanges.regressions | length' "$LATEST_BASELINE")
            CRITICAL=$(jq -r '[.detectedChanges.regressions[] | select(.severity == "critical")] | length' "$LATEST_BASELINE")
            
            echo "health_score=$HEALTH_SCORE" >> $GITHUB_OUTPUT
            echo "regression_count=$REGRESSIONS" >> $GITHUB_OUTPUT
            echo "critical_count=$CRITICAL" >> $GITHUB_OUTPUT
            echo "has_critical=$( [ "$CRITICAL" -gt 0 ] && echo 'true' || echo 'false' )" >> $GITHUB_OUTPUT
            
            # Fail workflow if critical regressions detected
            if [ "$CRITICAL" -gt 0 ]; then
              echo "::error::Critical regressions detected! Health Score: $HEALTH_SCORE"
              exit 1
            fi
          fi
      
      - name: Create issue for critical regressions
        if: failure() && steps.check_regressions.outputs.has_critical == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const runId = '${{ github.run_id }}';
            const files = fs.readdirSync('performance-baselines/strategic')
              .filter(f => f.includes(runId) && f.endsWith('.json'));
            
            if (files.length === 0) {
              console.log('No baseline file found for this run');
              return;
            }
            
            const latestBaseline = JSON.parse(
              fs.readFileSync(`performance-baselines/strategic/${files[0]}`, 'utf8')
            );
            
            const criticalRegressions = latestBaseline.detectedChanges.regressions
              .filter(r => r.severity === 'critical');
            
            const issueBody = `## Critical Performance Regressions Detected
            
**Health Score:** ${latestBaseline.detectedChanges.healthScore}/100 🔴
**Trend:** ${latestBaseline.comparisonBaseline.trend}
**Run:** ${{ github.run_id }}

### Critical Regressions

${criticalRegressions.map(r => `- **${r.type.toUpperCase()}:** ${r.description}`).join('\n')}

### Details

See the full trend report in the [repository](../../tree/${{ github.ref_name }}/performance-baselines/strategic) after the next commit.

**Baseline:** ${latestBaseline.timestamp}
**Commit:** ${latestBaseline.commit}
            `;
            
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `perf(critical): ${criticalRegressions.length} critical regression(s) detected - Health ${latestBaseline.detectedChanges.healthScore}/100`,
              body: issueBody,
              labels: ['performance', 'regression', 'critical', 'automated']
            });
      
      - name: Comment on recent PRs with health score
        if: steps.check_regressions.outputs.health_score < 75
        uses: actions/github-script@v7
        with:
          script: |
            const healthScore = ${{ steps.check_regressions.outputs.health_score }};
            const emoji = healthScore >= 75 ? '🟡' : healthScore >= 50 ? '🟠' : '🔴';
            
            const comment = `### 📊 Performance Health Update
            
**Health Score:** ${healthScore}/100 ${emoji}
**Regressions Detected:** ${{ steps.check_regressions.outputs.regression_count }}

Performance has degraded below the healthy threshold. Please review the trend report in the [baselines directory](../../tree/${{ github.ref_name }}/performance-baselines/strategic).
            `;
            
            // Find recent merged PRs and comment
            const { data: prs } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'closed',
              sort: 'updated',
              direction: 'desc',
              per_page: 5
            });
            
            for (const pr of prs) {
              if (pr.merged_at) {
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: pr.number,
                  body: comment
                });
                break; // Only comment on most recent merged PR
              }
            }
